/**
 * Vercel Serverless Function — wraps the Express app.
 * Tries pre-compiled bundle first (built by esbuild), falls back to direct import.
 */
let handler;

try {
  // Fast path: pre-compiled bundle (generated by buildCommand)
  const mod = await import('./_compiled.mjs');
  handler = mod.default;
} catch (e1) {
  try {
    // Fallback: import server directly (relies on @vercel/node TypeScript support)
    const mod = await import('../server/index.js');
    handler = mod.default;
  } catch (e2) {
    // If both fail, return diagnostic error
    handler = (req, res) => {
      res.statusCode = 500;
      res.setHeader('Content-Type', 'application/json');
      res.end(JSON.stringify({
        error: 'Server failed to initialize',
        compiled: e1.message,
        direct: e2.message,
      }));
    };
  }
}

export default handler;
